from __future__ import annotations

CROP_PROFILES: dict[str, dict] = {
    "maize": {
        "label": "Maize",
        "season": "Kharif",
        "supports_disease": True,
        "supports_yield": True,
        "ideal_rainfall_mm": 410.0,
        "ideal_temp_c": 28.5,
        "ideal_ph": 7.0,
        "organic_carbon_floor": 0.95,
        "nitrogen_target": 58.0,
        "phosphorus_target": 22.0,
        "potassium_target": 195.0,
        "season_months": [6, 7, 8, 9, 10],
        "yield_reference_districts": ["Faisalabad", "Peshawar", "Mardan"],
    },
    "wheat": {
        "label": "Wheat",
        "season": "Rabi",
        "supports_disease": False,
        "supports_yield": True,
        "ideal_rainfall_mm": 260.0,
        "ideal_temp_c": 21.0,
        "ideal_ph": 7.3,
        "organic_carbon_floor": 0.9,
        "nitrogen_target": 50.0,
        "phosphorus_target": 20.0,
        "potassium_target": 175.0,
        "season_months": [11, 12, 1, 2, 3, 4],
        "yield_reference_districts": ["Faisalabad", "Multan", "Peshawar"],
    },
    "rice": {
        "label": "Rice",
        "season": "Kharif",
        "supports_disease": False,
        "supports_yield": True,
        "ideal_rainfall_mm": 560.0,
        "ideal_temp_c": 29.0,
        "ideal_ph": 6.7,
        "organic_carbon_floor": 1.05,
        "nitrogen_target": 64.0,
        "phosphorus_target": 24.0,
        "potassium_target": 210.0,
        "season_months": [6, 7, 8, 9, 10],
        "yield_reference_districts": ["Lahore", "Faisalabad", "Hyderabad"],
    },
    "cotton": {
        "label": "Cotton",
        "season": "Kharif",
        "supports_disease": True,
        "supports_yield": True,
        "ideal_rainfall_mm": 345.0,
        "ideal_temp_c": 29.5,
        "ideal_ph": 7.2,
        "organic_carbon_floor": 0.85,
        "nitrogen_target": 54.0,
        "phosphorus_target": 21.0,
        "potassium_target": 188.0,
        "season_months": [5, 6, 7, 8, 9, 10, 11],
        "yield_reference_districts": ["Bahawalpur", "Multan", "Hyderabad"],
    },
    "sugarcane": {
        "label": "Sugarcane",
        "season": "Kharif",
        "supports_disease": True,
        "supports_yield": True,
        "ideal_rainfall_mm": 525.0,
        "ideal_temp_c": 27.5,
        "ideal_ph": 6.8,
        "organic_carbon_floor": 1.15,
        "nitrogen_target": 70.0,
        "phosphorus_target": 24.0,
        "potassium_target": 220.0,
        "season_months": [11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "yield_reference_districts": ["Faisalabad", "Hyderabad", "Mardan"],
    },
    "tomato": {
        "label": "Tomato",
        "season": "Mixed",
        "supports_disease": True,
        "supports_yield": False,
        "ideal_rainfall_mm": 320.0,
        "ideal_temp_c": 24.0,
        "ideal_ph": 6.5,
        "organic_carbon_floor": 1.1,
        "nitrogen_target": 48.0,
        "phosphorus_target": 28.0,
        "potassium_target": 240.0,
        "season_months": [1, 2, 3, 10, 11, 12],
        "yield_reference_districts": ["Lahore", "Peshawar"],
    },
    "potato": {
        "label": "Potato",
        "season": "Rabi",
        "supports_disease": True,
        "supports_yield": False,
        "ideal_rainfall_mm": 295.0,
        "ideal_temp_c": 20.0,
        "ideal_ph": 6.2,
        "organic_carbon_floor": 1.0,
        "nitrogen_target": 46.0,
        "phosphorus_target": 26.0,
        "potassium_target": 230.0,
        "season_months": [11, 12, 1, 2, 3],
        "yield_reference_districts": ["Peshawar", "Mardan", "Lahore"],
    },
}


DISTRICT_PROFILES: dict[str, dict] = {
    "Faisalabad": {
        "province": "Punjab",
        "climate_band": "irrigated plains",
        "rainfall_baseline_mm": 385.0,
        "avg_temp_c": 27.7,
        "soil_ph": 7.1,
        "organic_carbon_pct": 1.03,
        "lat": 31.4180,
        "lon": 73.0790,
    },
    "Lahore": {
        "province": "Punjab",
        "climate_band": "canal command",
        "rainfall_baseline_mm": 405.0,
        "avg_temp_c": 27.9,
        "soil_ph": 7.0,
        "organic_carbon_pct": 1.05,
        "lat": 31.5204,
        "lon": 74.3587,
    },
    "Multan": {
        "province": "Punjab",
        "climate_band": "southern irrigated",
        "rainfall_baseline_mm": 330.0,
        "avg_temp_c": 29.6,
        "soil_ph": 7.5,
        "organic_carbon_pct": 0.86,
        "lat": 30.1575,
        "lon": 71.5249,
    },
    "Bahawalpur": {
        "province": "Punjab",
        "climate_band": "arid canal fringe",
        "rainfall_baseline_mm": 305.0,
        "avg_temp_c": 30.2,
        "soil_ph": 7.8,
        "organic_carbon_pct": 0.79,
        "lat": 29.3956,
        "lon": 71.6836,
    },
    "Hyderabad": {
        "province": "Sindh",
        "climate_band": "lower Indus",
        "rainfall_baseline_mm": 245.0,
        "avg_temp_c": 30.4,
        "soil_ph": 7.6,
        "organic_carbon_pct": 0.73,
        "lat": 25.3960,
        "lon": 68.3578,
    },
    "Sukkur": {
        "province": "Sindh",
        "climate_band": "upper Sindh",
        "rainfall_baseline_mm": 210.0,
        "avg_temp_c": 31.1,
        "soil_ph": 7.7,
        "organic_carbon_pct": 0.68,
        "lat": 27.7052,
        "lon": 68.8574,
    },
    "Peshawar": {
        "province": "Khyber Pakhtunkhwa",
        "climate_band": "north-west plains",
        "rainfall_baseline_mm": 360.0,
        "avg_temp_c": 24.7,
        "soil_ph": 7.3,
        "organic_carbon_pct": 0.96,
        "lat": 34.0151,
        "lon": 71.5249,
    },
    "Mardan": {
        "province": "Khyber Pakhtunkhwa",
        "climate_band": "foothill plain",
        "rainfall_baseline_mm": 395.0,
        "avg_temp_c": 24.2,
        "soil_ph": 7.2,
        "organic_carbon_pct": 1.02,
        "lat": 34.1989,
        "lon": 72.0401,
    },
}


DISEASE_CLASS_DETAILS: dict[str, dict[str, object]] = {
    "cotton_healthy": {"crop": "cotton", "display_name": "Healthy"},
    "cotton_alternaria_leaf_spot": {"crop": "cotton", "display_name": "Alternaria Leaf Spot"},
    "cotton_bacterial_blight": {"crop": "cotton", "display_name": "Bacterial Blight"},
    "cotton_fusarium_wilt": {"crop": "cotton", "display_name": "Fusarium Wilt"},
    "cotton_verticillium_wilt": {"crop": "cotton", "display_name": "Verticillium Wilt"},
    "maize_healthy": {"crop": "maize", "display_name": "Healthy"},
    "maize_common_rust": {"crop": "maize", "display_name": "Common Rust"},
    "maize_northern_leaf_blight": {"crop": "maize", "display_name": "Northern Leaf Blight"},
    "potato_healthy": {"crop": "potato", "display_name": "Healthy"},
    "potato_early_blight": {"crop": "potato", "display_name": "Early Blight"},
    "potato_late_blight": {"crop": "potato", "display_name": "Late Blight"},
    "sugarcane_healthy": {"crop": "sugarcane", "display_name": "Healthy"},
    "sugarcane_brown_rust": {"crop": "sugarcane", "display_name": "Brown Rust"},
    "sugarcane_pokkah_boeng": {"crop": "sugarcane", "display_name": "Pokkah Boeng"},
    "sugarcane_smut": {"crop": "sugarcane", "display_name": "Smut"},
    "sugarcane_viral_disease": {"crop": "sugarcane", "display_name": "Viral Disease"},
    "sugarcane_yellow_leaf": {"crop": "sugarcane", "display_name": "Yellow Leaf"},
    "tomato_healthy": {"crop": "tomato", "display_name": "Healthy"},
    "tomato_bacterial_spot": {"crop": "tomato", "display_name": "Bacterial Spot"},
    "tomato_early_blight": {"crop": "tomato", "display_name": "Early Blight"},
    "tomato_late_blight": {"crop": "tomato", "display_name": "Late Blight"},
    "tomato_leaf_mold": {"crop": "tomato", "display_name": "Leaf Mold"},
    "tomato_septoria_leaf_spot": {"crop": "tomato", "display_name": "Septoria Leaf Spot"},
    "tomato_tomato_yellow_leaf_curl_virus": {
        "crop": "tomato",
        "display_name": "Tomato Yellow Leaf Curl Virus",
    },
}

DISEASE_CLASSES = list(DISEASE_CLASS_DETAILS)
