# Generated by Django 5.2.12 on 2026-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('crop', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('action', models.TextField()),
                ('rationale', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['crop', 'category', 'title'],
            },
        ),
    ]
