# Generated by Django 5.2.12 on 2026-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='uploads/originals/')),
                ('overlay_image', models.ImageField(blank=True, upload_to='uploads/overlays/')),
                ('predicted_label', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('summary', models.TextField()),
                ('probabilities', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('plant_coverage_pct', models.FloatField(default=0.0)),
                ('hotspot_pct', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
